# Generated by Django 3.1.12 on 2025-06-15 04:11

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('latitud', models.FloatField(blank=True, default=0.0, null=True)),
                ('longitud', models.FloatField(blank=True, default=0.0, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Frase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frase', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=100, unique=True)),
                ('remitente', models.CharField(max_length=255)),
                ('direccion_recoleccion', models.TextField()),
                ('receptor', models.CharField(max_length=255)),
                ('direccion_entrega', models.TextField()),
                ('descripcion', models.TextField()),
                ('peso', models.FloatField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('estado_paquete', models.CharField(choices=[('En tránsito', 'En tránsito'), ('Recolección', 'Recolección'), ('Entregado', 'Entregado'), ('Retrasado', 'Retrasado'), ('Cancelado', 'Cancelado')], default='En tránsito', max_length=50)),
                ('estado_actual', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paquetes', to='paquetes.estado')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contraseña', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudEnvio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remitente_nombre', models.CharField(max_length=100)),
                ('remitente_colonia', models.CharField(max_length=100)),
                ('remitente_calle', models.CharField(max_length=100)),
                ('remitente_numero', models.CharField(max_length=20)),
                ('remitente_cp', models.CharField(max_length=5)),
                ('remitente_estado', models.CharField(max_length=100)),
                ('destinatario_nombre', models.CharField(max_length=100)),
                ('destinatario_colonia', models.CharField(max_length=100)),
                ('destinatario_calle', models.CharField(max_length=100)),
                ('destinatario_numero', models.CharField(max_length=20)),
                ('destinatario_cp', models.CharField(max_length=5)),
                ('destinatario_estado', models.CharField(max_length=100)),
                ('peso', models.FloatField()),
                ('dimensiones', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('cotizacion', models.FloatField()),
                ('numero_seguimiento', models.CharField(max_length=20, unique=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paquetes.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=False)),
                ('estado_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas_destino', to='paquetes.estado')),
                ('estado_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas_origen', to='paquetes.estado')),
                ('frase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to='paquetes.frase')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to='paquetes.paquete')),
            ],
        ),
        migrations.AddField(
            model_name='paquete',
            name='uusuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paquetes.usuario'),
        ),
    ]
